title: Da Report
author: Anders Schneiderman
email: your-email@domain.com
description:  Building a power user ecosystem that helps companies and the community

# Menu data for sitewide navigation
navigation_links:
  # - name:  About
    # link: 'about/'
  - name: Intro
    link: "intro/"
  - name: Why
    link: 'why/'
  - name: How
    link: 'creative-dataviz'
  - name: Next
    link: 'what-next/'
  - name: Conclusion
    link: 'conclusion/'

